FROM python:3.11-slim

WORKDIR /app

# Встановлюємо залежності
RUN pip install --no-cache-dir flask prometheus_client werkzeug

# Копіюємо код автентифікації
COPY auth_server.py /app/

# (опційно) якщо хочеш мати початковий users.db з репозиторію:
# COPY users.db /app/users.db

EXPOSE 5005
EXPOSE 9200

CMD ["python", "auth_server.py"]
